"use client"

import { useState, useEffect } from "react"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { ArrowLeft, RefreshCw, Calendar, Clock, CheckCircle } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { useToast } from "@/hooks/use-toast"
import AOS from "aos"
import "aos/dist/aos.css"

export default function AutoBlogDashboard() {
  const router = useRouter()
  const { toast } = useToast()
  const [loading, setLoading] = useState(false)
  const [generatingPost, setGeneratingPost] = useState(false)
  const [autoBlogPosts, setAutoBlogPosts] = useState([])
  const [activeTab, setActiveTab] = useState("settings")
  const [isGenerating, setIsGenerating] = useState(false)
  const [generationError, setGenerationError] = useState(null)

  useEffect(() => {
    AOS.init({
      duration: 800,
      once: false,
    })

    fetchAutoBlogPosts()
  }, [])

  const fetchAutoBlogPosts = async () => {
    try {
      setLoading(true)
      const response = await fetch("/api/blog")
      if (response.ok) {
        const allPosts = await response.json()
        // Filter only auto-generated posts
        const autoPosts = allPosts.filter((post) => post.autoGenerated === true)
        setAutoBlogPosts(autoPosts)
      }
    } catch (error) {
      console.error("Error fetching auto-generated blog posts:", error)
      toast({
        title: "Error",
        description: "Failed to fetch auto-generated blog posts",
        variant: "destructive",
      })
    } finally {
      setLoading(false)
    }
  }

  const handleGeneratePost = async (timeOfDay = "morning") => {
    setIsGenerating(true)
    setGenerationError(null)

    try {
      const response = await fetch(`/api/auto-blog?timeOfDay=${timeOfDay}`)
      const data = await response.json()

      if (!response.ok) {
        throw new Error(data.error || data.details || "Failed to generate blog post")
      }

      toast({
        title: "Success",
        description: `Blog post "${data.title}" generated successfully!`,
      })

      // Refresh the list of posts
      router.refresh()

      // Add a delay before redirecting to ensure the new post is available
      setTimeout(() => {
        router.push(`/admin/blog/${data.id}`)
      }, 1000)
    } catch (error) {
      console.error("Error generating blog post:", error)
      setGenerationError(error.message)

      toast({
        title: "Error",
        description: error.message || "Failed to generate blog post",
        variant: "destructive",
      })
    } finally {
      setIsGenerating(false)
    }
  }

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
      hour: "numeric",
      minute: "numeric",
    })
  }

  return (
    <div className="container mx-auto px-4 py-12 md:px-6 md:py-20">
      <div className="mx-auto max-w-6xl">
        <Link href="/admin" className="mb-8 inline-flex items-center text-sm font-medium" data-aos="fade-up">
          <ArrowLeft className="mr-2 h-4 w-4" />
          Back to Dashboard
        </Link>

        <div className="mb-8 text-center" data-aos="fade-up">
          <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl">Automated Blog Posts</h1>
          <p className="mt-4 text-xl text-muted-foreground">Manage AI-generated blog posts about web development</p>
        </div>

        <Tabs defaultValue="settings" value={activeTab} onValueChange={setActiveTab} className="mb-20">
          <TabsList className="mb-8 flex w-full flex-wrap justify-center gap-2">
            <TabsTrigger value="settings">Settings & Generation</TabsTrigger>
            <TabsTrigger value="history">Post History</TabsTrigger>
          </TabsList>

          <TabsContent value="settings">
            <div className="grid gap-6 md:grid-cols-2">
              <Card data-aos="fade-up">
                <CardHeader>
                  <CardTitle>Generate Blog Post</CardTitle>
                  <CardDescription>Manually trigger the generation of a new blog post</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    <p className="text-sm text-muted-foreground">
                      Generate a new blog post about web development using Gemini AI. The post will include content
                      generated by AI and an image from Unsplash.
                    </p>
                    {generationError && (
                      <div className="mt-4 rounded-md bg-destructive/10 p-4 text-destructive">
                        <h3 className="font-semibold">Error Generating Blog Post</h3>
                        <p>{generationError}</p>
                        <p className="mt-2 text-sm">
                          Please ensure your Gemini API key is correctly configured in the environment variables.
                        </p>
                      </div>
                    )}
                    <div className="flex flex-col gap-4 sm:flex-row">
                      <Button onClick={() => handleGeneratePost("morning")} disabled={isGenerating} className="flex-1">
                        {isGenerating ? (
                          <RefreshCw className="mr-2 h-4 w-4 animate-spin" />
                        ) : (
                          <Calendar className="mr-2 h-4 w-4" />
                        )}
                        Generate Morning Post
                      </Button>
                      <Button onClick={() => handleGeneratePost("evening")} disabled={isGenerating} className="flex-1">
                        {isGenerating ? (
                          <RefreshCw className="mr-2 h-4 w-4 animate-spin" />
                        ) : (
                          <Clock className="mr-2 h-4 w-4" />
                        )}
                        Generate Evening Post
                      </Button>
                    </div>
                  </div>
                </CardContent>
              </Card>

              <Card data-aos="fade-up" data-aos-delay="100">
                <CardHeader>
                  <CardTitle>Automated Schedule</CardTitle>
                  <CardDescription>Configure the automatic generation schedule</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    <p className="text-sm text-muted-foreground">Blog posts are automatically generated twice daily:</p>
                    <ul className="space-y-2">
                      <li className="flex items-center">
                        <CheckCircle className="mr-2 h-4 w-4 text-green-500" />
                        <span>Morning post: 8:00 AM</span>
                      </li>
                      <li className="flex items-center">
                        <CheckCircle className="mr-2 h-4 w-4 text-green-500" />
                        <span>Evening post: 6:00 PM</span>
                      </li>
                    </ul>
                    <p className="text-sm text-muted-foreground mt-4">
                      This schedule is configured using Vercel Cron Jobs and can be adjusted in the project settings.
                    </p>
                  </div>
                </CardContent>
              </Card>
            </div>

            <Card className="mt-6" data-aos="fade-up" data-aos-delay="200">
              <CardHeader>
                <CardTitle>How It Works</CardTitle>
                <CardDescription>Understanding the automated blog post generation system</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <p>
                    The automated blog post system uses Google's Gemini AI to generate educational content about web
                    development topics. Each post includes:
                  </p>
                  <ul className="list-disc pl-6 space-y-2">
                    <li>
                      <strong>AI-Generated Content:</strong> Educational articles about various web development topics
                    </li>
                    <li>
                      <strong>Relevant Images:</strong> Automatically selected from Unsplash based on the topic
                    </li>
                    <li>
                      <strong>Proper Formatting:</strong> Content is formatted with Markdown for readability
                    </li>
                    <li>
                      <strong>SEO Optimization:</strong> Includes relevant tags, excerpts, and metadata
                    </li>
                  </ul>
                  <p className="mt-4">
                    Posts are automatically published to your blog and notifications are sent to your subscribers. You
                    can edit or delete these posts just like manually created ones.
                  </p>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="history">
            <Card data-aos="fade-up">
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div>
                    <CardTitle>Generated Posts History</CardTitle>
                    <CardDescription>View all AI-generated blog posts</CardDescription>
                  </div>
                  <Button variant="outline" onClick={fetchAutoBlogPosts} disabled={loading}>
                    {loading ? <RefreshCw className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}
                  </Button>
                </div>
              </CardHeader>
              <CardContent>
                {loading ? (
                  <div className="flex justify-center py-8">
                    <div className="h-8 w-8 animate-spin rounded-full border-2 border-primary border-t-transparent"></div>
                  </div>
                ) : autoBlogPosts.length === 0 ? (
                  <div className="py-8 text-center text-muted-foreground">
                    <p>No auto-generated blog posts found.</p>
                    <p className="mt-2">Generate your first post using the controls in the Settings tab.</p>
                  </div>
                ) : (
                  <div className="space-y-4">
                    {autoBlogPosts.map((post) => (
                      <div key={post.id} className="border-b pb-4 last:border-0 last:pb-0">
                        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between">
                          <div>
                            <h3 className="font-medium">{post.title}</h3>
                            <p className="text-sm text-muted-foreground">
                              {post.timeOfDay === "morning" ? "Morning" : "Evening"} post • {post.date}
                            </p>
                          </div>
                          <div className="mt-2 flex gap-2 sm:mt-0">
                            <Link href={`/blog/${post.slug}`}>
                              <Button variant="outline" size="sm">
                                View
                              </Button>
                            </Link>
                            <Link href={`/admin/blog/${post.id}`}>
                              <Button variant="outline" size="sm">
                                Edit
                              </Button>
                            </Link>
                          </div>
                        </div>
                        <p className="mt-2 text-sm">{post.excerpt}</p>
                        <div className="mt-2 flex flex-wrap gap-1">
                          {post.tags &&
                            post.tags.map((tag, index) => (
                              <span key={index} className="rounded-full bg-muted px-2.5 py-0.5 text-xs">
                                {tag}
                              </span>
                            ))}
                        </div>
                        <p className="mt-2 text-xs text-muted-foreground">Generated: {formatDate(post.generatedAt)}</p>
                      </div>
                    ))}
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  )
}
