"use client"

import { useState, useEffect } from "react"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { ArrowLeft, RefreshCw, Calendar, Clock, CheckCircle } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { useToast } from "@/hooks/use-toast"
import AOS from "aos"
import "aos/dist/aos.css"

export default function AutoBlogDashboard() {
  const router = useRouter()
  const { toast } = useToast()
  const [loading, setLoading] = useState(false)
  const [generatingPost, setGeneratingPost] = useState(false)
  const [autoBlogPosts, setAutoBlogPosts] = useState([])
  const [activeTab, setActiveTab] = useState("settings")
  const [isGenerating, setIsGenerating] = useState(false)
  const [generationError, setGenerationError] = useState(null)

  useEffect(() => {
    AOS.init({
      duration: 800,
      once: false,
    })

    fetchAutoBlogPosts()
  }, [])

  const fetchAutoBlogPosts = async () => {
    try {
      setLoading(true)
      const response = await fetch("/api/blog")
      if (response.ok) {
        const allPosts = await response.json()
        // Filter only auto-generated posts
        const autoPosts = allPosts.filter((post) => post.autoGenerated === true)
        setAutoBlogPosts(autoPosts)
      }
    } catch (error) {
      console.error("Error fetching auto-generated blog posts:", error)
      toast({
        title: "Error",
        description: "Failed to fetch auto-generated blog posts",
        variant: "destructive",
      })
    } finally {
      setLoading(false)
    }
  }

  const handleGeneratePost = async (timeOfDay = "morning") => {
    setIsGenerating(true)
    setGenerationError(null)

    try {
      const response = await fetch(`/api/auto-blog?timeOfDay=${timeOfDay}`)
      const data = await response.json()

      if (!response.ok) {
        throw new Error(data.error || data.details || "Failed to generate blog post")
      }

      toast({
        title: "Success",
        description: `Blog post "${data.title}" generated successfully!`,
      })

      // Refresh the list of posts
      router.refresh()

      // Add a delay before redirecting to ensure the new post is available
      setTimeout(() => {
        router.push(`/admin/blog/${data.id}`)
      }, 1000)
    } catch (error) {
      console.error("Error generating blog post:", error)
      setGenerationError(error.message)

      toast({
        title: "Error",
        description: error.message || "Failed to generate blog post",
        variant: "destructive",
      })
    } finally {
      setIsGenerating(false)
    }
  }

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
      hour: "numeric",
      minute: "numeric",
    })
  }

  return (
    <div className="container mx-auto px-4 py-12 md:px-6 md:py-20">
      <div className="mx-auto max-w-6xl">
        <Link href="/admin" className="mb-8 inline-flex items-center text-sm font-medium" data-aos="fade-up">
          <ArrowLeft className="mr-2 h-4 w-4" />
          Back to Dashboard
        </Link>

        <div className="mb-8 text-center" data-aos="fade-up">
          <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl">Automated Blog Posts</h1>
          <p className="mt-4 text-xl text-muted-foreground">
            AI-powered blog generation using OpenRouter AI with comprehensive tech categories
          </p>
        </div>

        <Tabs defaultValue="settings" value={activeTab} onValueChange={setActiveTab} className="mb-20">
          <TabsList className="mb-8 flex w-full flex-wrap justify-center gap-2">
            <TabsTrigger value="settings">Settings & Generation</TabsTrigger>
            <TabsTrigger value="history">Post History</TabsTrigger>
            <TabsTrigger value="categories">Categories</TabsTrigger>
          </TabsList>

          <TabsContent value="settings">
            <div className="grid gap-6 md:grid-cols-2">
              <Card data-aos="fade-up">
                <CardHeader>
                  <CardTitle>Generate Blog Post</CardTitle>
                  <CardDescription>Manually trigger the generation of a new blog post</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    <p className="text-sm text-muted-foreground">
                      Generate a new blog post using OpenRouter AI with DeepSeek Chat v3.1 model. Posts cover
                      comprehensive tech topics with SEO optimization.
                    </p>
                    {generationError && (
                      <div className="mt-4 rounded-md bg-destructive/10 p-4 text-destructive">
                        <h3 className="font-semibold">Error Generating Blog Post</h3>
                        <p>{generationError}</p>
                        <p className="mt-2 text-sm">
                          Please ensure your OpenRouter API key is correctly configured in the environment variables.
                        </p>
                      </div>
                    )}
                    <div className="flex flex-col gap-4 sm:flex-row">
                      <Button onClick={() => handleGeneratePost("morning")} disabled={isGenerating} className="flex-1">
                        {isGenerating ? (
                          <RefreshCw className="mr-2 h-4 w-4 animate-spin" />
                        ) : (
                          <Calendar className="mr-2 h-4 w-4" />
                        )}
                        Generate Morning Post
                      </Button>
                      <Button onClick={() => handleGeneratePost("evening")} disabled={isGenerating} className="flex-1">
                        {isGenerating ? (
                          <RefreshCw className="mr-2 h-4 w-4 animate-spin" />
                        ) : (
                          <Clock className="mr-2 h-4 w-4" />
                        )}
                        Generate Evening Post
                      </Button>
                    </div>
                  </div>
                </CardContent>
              </Card>

              <Card data-aos="fade-up" data-aos-delay="100">
                <CardHeader>
                  <CardTitle>Automated Schedule</CardTitle>
                  <CardDescription>Configure the automatic generation schedule</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    <p className="text-sm text-muted-foreground">
                      Blog posts are automatically generated every 2 hours:
                    </p>
                    <ul className="space-y-2">
                      <li className="flex items-center">
                        <CheckCircle className="mr-2 h-4 w-4 text-green-500" />
                        <span>Continuous generation: Every 2 hours</span>
                      </li>
                      <li className="flex items-center">
                        <CheckCircle className="mr-2 h-4 w-4 text-green-500" />
                        <span>Content variety: 6 major categories</span>
                      </li>
                      <li className="flex items-center">
                        <CheckCircle className="mr-2 h-4 w-4 text-green-500" />
                        <span>Quality: SEO-optimized with examples</span>
                      </li>
                    </ul>
                    <p className="text-sm text-muted-foreground mt-4">
                      This schedule generates 12 high-quality posts daily using Vercel Cron Jobs.
                    </p>
                  </div>
                </CardContent>
              </Card>
            </div>

            <Card className="mt-6" data-aos="fade-up" data-aos-delay="200">
              <CardHeader>
                <CardTitle>How It Works</CardTitle>
                <CardDescription>Understanding the enhanced automated blog post generation system</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <p>
                    The automated blog system uses OpenRouter AI with DeepSeek Chat v3.1 to generate comprehensive
                    educational content across 6 major tech categories:
                  </p>
                  <ul className="list-disc pl-6 space-y-2">
                    <li>
                      <strong>Web Development:</strong> Frontend, Backend, Full-Stack, Security, Testing, Performance,
                      Emerging Tech
                    </li>
                    <li>
                      <strong>Mobile App Development:</strong> iOS, Android, Cross-Platform, UI/UX, Performance,
                      Security, App Store
                    </li>
                    <li>
                      <strong>DevOps & Deployment:</strong> CI/CD, Cloud, Infrastructure, Monitoring, Scaling, Security,
                      Cost Optimization
                    </li>
                    <li>
                      <strong>Software Engineering:</strong> Architecture, Design Patterns, Agile, Code Quality,
                      Testing, Version Control, Career
                    </li>
                    <li>
                      <strong>Tech Trends & Insights:</strong> AI, Blockchain, Edge Computing, Emerging Frameworks,
                      Industry Analysis
                    </li>
                    <li>
                      <strong>Security & Compliance:</strong> Web Security, Mobile Security, DevSecOps, Compliance,
                      Penetration Testing
                    </li>
                  </ul>
                  <div className="mt-4 space-y-2">
                    <p>
                      <strong>Content Types:</strong> Tutorials, Tips & Tricks, Getting Started Guides, Best Practices,
                      Deep Dives, Case Studies
                    </p>
                    <p>
                      <strong>Quality Features:</strong> SEO-optimized titles, comprehensive explanations, code
                      examples, practical applications
                    </p>
                    <p>
                      <strong>Length:</strong> 1200-1800 words per post for in-depth coverage
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="history">
            <Card data-aos="fade-up">
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div>
                    <CardTitle>Generated Posts History</CardTitle>
                    <CardDescription>View all AI-generated blog posts</CardDescription>
                  </div>
                  <Button variant="outline" onClick={fetchAutoBlogPosts} disabled={loading}>
                    {loading ? <RefreshCw className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}
                  </Button>
                </div>
              </CardHeader>
              <CardContent>
                {loading ? (
                  <div className="flex justify-center py-8">
                    <div className="h-8 w-8 animate-spin rounded-full border-2 border-primary border-t-transparent"></div>
                  </div>
                ) : autoBlogPosts.length === 0 ? (
                  <div className="py-8 text-center text-muted-foreground">
                    <p>No auto-generated blog posts found.</p>
                    <p className="mt-2">Generate your first post using the controls in the Settings tab.</p>
                  </div>
                ) : (
                  <div className="space-y-4">
                    {autoBlogPosts.map((post) => (
                      <div key={post.id} className="border-b pb-4 last:border-0 last:pb-0">
                        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between">
                          <div>
                            <h3 className="font-medium">{post.title}</h3>
                            <p className="text-sm text-muted-foreground">
                              {post.timeOfDay === "morning" ? "Morning" : "Evening"} post • {post.date}
                            </p>
                          </div>
                          <div className="mt-2 flex gap-2 sm:mt-0">
                            <Link href={`/blog/${post.slug}`}>
                              <Button variant="outline" size="sm">
                                View
                              </Button>
                            </Link>
                            <Link href={`/admin/blog/${post.id}`}>
                              <Button variant="outline" size="sm">
                                Edit
                              </Button>
                            </Link>
                          </div>
                        </div>
                        <p className="mt-2 text-sm">{post.excerpt}</p>
                        <div className="mt-2 flex flex-wrap gap-1">
                          {post.tags &&
                            post.tags.map((tag, index) => (
                              <span key={index} className="rounded-full bg-muted px-2.5 py-0.5 text-xs">
                                {tag}
                              </span>
                            ))}
                        </div>
                        <p className="mt-2 text-xs text-muted-foreground">Generated: {formatDate(post.generatedAt)}</p>
                      </div>
                    ))}
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="categories">
            <Card data-aos="fade-up">
              <CardHeader>
                <CardTitle>Blog Categories</CardTitle>
                <CardDescription>Overview of the 6 main categories used for automated blog generation</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4 md:grid-cols-2">
                  <div className="space-y-4">
                    <div className="border rounded-lg p-4">
                      <h3 className="font-semibold text-lg mb-2">Web Development</h3>
                      <p className="text-sm text-muted-foreground mb-2">
                        Frontend, Backend, Full-Stack, Security, Testing, Performance, Emerging Tech
                      </p>
                      <div className="flex flex-wrap gap-1">
                        {["React", "Next.js", "Node.js", "APIs", "Security", "Testing"].map((tag) => (
                          <span key={tag} className="bg-blue-100 text-blue-800 text-xs px-2 py-1 rounded">
                            {tag}
                          </span>
                        ))}
                      </div>
                    </div>

                    <div className="border rounded-lg p-4">
                      <h3 className="font-semibold text-lg mb-2">Mobile App Development</h3>
                      <p className="text-sm text-muted-foreground mb-2">
                        iOS, Android, Cross-Platform, UI/UX, Performance, Security, App Store
                      </p>
                      <div className="flex flex-wrap gap-1">
                        {["iOS", "Android", "Flutter", "React Native", "UI/UX", "Security"].map((tag) => (
                          <span key={tag} className="bg-green-100 text-green-800 text-xs px-2 py-1 rounded">
                            {tag}
                          </span>
                        ))}
                      </div>
                    </div>

                    <div className="border rounded-lg p-4">
                      <h3 className="font-semibold text-lg mb-2">DevOps & Deployment</h3>
                      <p className="text-sm text-muted-foreground mb-2">
                        CI/CD, Cloud, Infrastructure, Monitoring, Scaling, Security, Cost Optimization
                      </p>
                      <div className="flex flex-wrap gap-1">
                        {["CI/CD", "AWS", "Docker", "Kubernetes", "Monitoring", "Scaling"].map((tag) => (
                          <span key={tag} className="bg-purple-100 text-purple-800 text-xs px-2 py-1 rounded">
                            {tag}
                          </span>
                        ))}
                      </div>
                    </div>
                  </div>

                  <div className="space-y-4">
                    <div className="border rounded-lg p-4">
                      <h3 className="font-semibold text-lg mb-2">Software Engineering</h3>
                      <p className="text-sm text-muted-foreground mb-2">
                        Architecture, Design Patterns, Agile, Code Quality, Testing, Version Control, Career
                      </p>
                      <div className="flex flex-wrap gap-1">
                        {["Architecture", "Design Patterns", "Agile", "Clean Code", "Testing", "Git"].map((tag) => (
                          <span key={tag} className="bg-orange-100 text-orange-800 text-xs px-2 py-1 rounded">
                            {tag}
                          </span>
                        ))}
                      </div>
                    </div>

                    <div className="border rounded-lg p-4">
                      <h3 className="font-semibold text-lg mb-2">Tech Trends & Insights</h3>
                      <p className="text-sm text-muted-foreground mb-2">
                        AI, Blockchain, Edge Computing, Emerging Frameworks, Industry Analysis
                      </p>
                      <div className="flex flex-wrap gap-1">
                        {["AI", "Blockchain", "Web3", "Edge Computing", "Industry", "Trends"].map((tag) => (
                          <span key={tag} className="bg-red-100 text-red-800 text-xs px-2 py-1 rounded">
                            {tag}
                          </span>
                        ))}
                      </div>
                    </div>

                    <div className="border rounded-lg p-4">
                      <h3 className="font-semibold text-lg mb-2">Security & Compliance</h3>
                      <p className="text-sm text-muted-foreground mb-2">
                        Web Security, Mobile Security, DevSecOps, Compliance, Penetration Testing
                      </p>
                      <div className="flex flex-wrap gap-1">
                        {["Security", "OWASP", "Compliance", "GDPR", "DevSecOps", "Pentesting"].map((tag) => (
                          <span key={tag} className="bg-gray-100 text-gray-800 text-xs px-2 py-1 rounded">
                            {tag}
                          </span>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  )
}
