import { type NextRequest, NextResponse } from "next/server"
import { generateBlogPost } from "@/lib/openrouter-ai"
import { getUnsplashImage } from "@/lib/unsplash"
import { saveData } from "@/lib/file-storage"
import { logActivity } from "@/lib/activity-logger"
import slugify from "slugify"
import fs from "fs"
import path from "path"
import { buildSearchIndex } from "@/lib/search-index"

// Function to download an image from a URL and save it to the server
async function downloadAndSaveImage(imageUrl: string, fileName: string): Promise<string | null> {
  try {
    const response = await fetch(imageUrl)
    if (!response.ok) {
      throw new Error(`Failed to fetch image: ${response.status} ${response.statusText}`)
    }

    const buffer = await response.arrayBuffer()

    // Ensure directories exist
    const uploadsDir = path.join(process.cwd(), "uploads")
    const publicUploadsDir = path.join(process.cwd(), "public", "uploads")

    if (!fs.existsSync(uploadsDir)) {
      fs.mkdirSync(uploadsDir, { recursive: true })
    }

    if (!fs.existsSync(publicUploadsDir)) {
      fs.mkdirSync(publicUploadsDir, { recursive: true })
    }

    // Save to both locations
    const uploadPath = path.join(uploadsDir, fileName)
    const publicPath = path.join(publicUploadsDir, fileName)

    fs.writeFileSync(uploadPath, Buffer.from(buffer))
    fs.writeFileSync(publicPath, Buffer.from(buffer))

    return `/uploads/${fileName}`
  } catch (error) {
    console.error("Error downloading and saving image:", error)
    return null
  }
}

// POST /api/auto-blog - Generate and publish a blog post
export async function POST(request: NextRequest) {
  try {
    // Check for authorization (you might want to add a secret key check here)
    const authHeader = request.headers.get("authorization")
    if (!process.env.OPENROUTER_API_KEY || !process.env.UNSPLASH_ACCESS_KEY) {
      return NextResponse.json({ error: "API keys not configured" }, { status: 500 })
    }

    if (process.env.OPENROUTER_API_KEY === "") {
      return NextResponse.json({ error: "OpenRouter API key is empty" }, { status: 500 })
    }

    // Get the time of day from the request or default to "morning"
    const { timeOfDay = "morning" } = await request.json()

    const blogData = await generateBlogPost(timeOfDay as "morning" | "evening")

    if (
      blogData.content.includes("Content Generation Error") ||
      blogData.content.includes("OpenRouter AI Integration Issue")
    ) {
      console.error("Received fallback content from OpenRouter AI, indicating an error occurred")
      return NextResponse.json(
        {
          error: "Failed to generate blog content with OpenRouter AI",
          details: blogData.content.includes("API key") ? "API key configuration issue" : "Content generation error",
        },
        { status: 500 },
      )
    }

    // Get a relevant image from Unsplash
    const imageUrl = await getUnsplashImage(blogData.topic)

    // Download and save the image
    let imagePath = null
    if (imageUrl) {
      const fileName = `${slugify(blogData.title, { lower: true })}-${Date.now()}.jpg`
      imagePath = await downloadAndSaveImage(imageUrl, fileName)
    }

    // Generate a slug from the title
    const slug = slugify(blogData.title, { lower: true, strict: true })

    // Prepare the blog post data
    const postData = {
      title: blogData.title,
      slug,
      content: blogData.content,
      excerpt: blogData.excerpt,
      tags: blogData.tags,
      category: blogData.category,
      imagePath: imagePath || "/placeholder.svg?height=600&width=1200&text=Web+Development",
      author: "Ngoma Benjamin",
      authorImage: "/placeholder.svg?height=100&width=100&text=NB",
      authorBio: "Full-stack developer and founder of 301Inc with a passion for web technologies.",
      date: new Date().toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      }),
      readTime: `${Math.max(1, Math.ceil(blogData.content.length / 1000))} min read`,
      status: "published",
      featured: false,
      autoGenerated: true,
      generatedAt: new Date().toISOString(),
      timeOfDay,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }

    // Save the blog post
    const id = await saveData("blog", postData)

    // Log the activity
    await logActivity("created", "blog", id, postData.title)

    try {
      await buildSearchIndex()
      console.log("Search index updated after creating auto-generated blog post")
    } catch (indexError) {
      console.error("Error updating search index:", indexError)
      // Continue even if search index update fails
    }

    // Notify subscribers about the new post (reusing existing functionality)
    try {
      const { sendNewsletterToAll } = await import("@/lib/email")
      const subject = `New Blog Post: ${postData.title}`
      const content = `
        <p>Hello,</p>
        <p>A new blog post has been published on Ngoma Benjamin's portfolio website:</p>
        <h2>${postData.title}</h2>
        <p>${postData.excerpt}</p>
        <p>Click the button below to read the full article:</p>
      `

      await sendNewsletterToAll(subject, content, [postData])
    } catch (emailError) {
      console.error("Error sending blog post notification:", emailError)
      // Continue even if email fails
    }

    return NextResponse.json({
      success: true,
      id,
      title: postData.title,
      slug: postData.slug,
      category: postData.category,
    })
  } catch (error) {
    console.error("Error generating and publishing blog post:", error)
    return NextResponse.json({ error: "Failed to generate and publish blog post" }, { status: 500 })
  }
}

// GET /api/auto-blog - Trigger blog post generation (for testing)
export async function GET(request: NextRequest) {
  try {
    const timeOfDay = (request.nextUrl.searchParams.get("timeOfDay") as "morning" | "evening") || "morning"

    // Create a POST request to the same endpoint
    const response = await fetch(`${request.nextUrl.origin}/api/auto-blog`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: request.headers.get("authorization") || "",
      },
      body: JSON.stringify({ timeOfDay }),
    })

    const data = await response.json()
    console.log("Auto blog post generation triggered via GET:", data)
    return NextResponse.json(data)
  } catch (error) {
    console.error("Error triggering blog post generation:", error)
    return NextResponse.json({ error: "Failed to trigger blog post generation" }, { status: 500 })
  }
}
