import { generateBlogPost } from "./openrouter-ai"
import { getUnsplashImage } from "./unsplash"
import { saveData, saveImage } from "./file-storage"
import { logActivity } from "./activity-logger"
import slugify from "slugify"

// Function to download an image from a URL and save it to the server
async function downloadAndSaveImage(imageUrl: string, fileName: string): Promise<string | null> {
  try {
    const response = await fetch(imageUrl)
    if (!response.ok) {
      throw new Error(`Failed to fetch image: ${response.status} ${response.statusText}`)
    }

    const buffer = await response.arrayBuffer()
    const file = new File([buffer], fileName, { type: response.headers.get("content-type") || "image/jpeg" })

    // Use the existing saveImage function from file-storage.ts
    return await saveImage(file)
  } catch (error) {
    console.error("Error downloading and saving image:", error)
    return null
  }
}

// Function to generate and publish a blog post
export async function generateAndPublishBlogPost(
  timeOfDay: "morning" | "evening",
): Promise<{ success: boolean; id?: string; error?: string }> {
  try {
    if (!process.env.OPENROUTER_API_KEY || !process.env.UNSPLASH_ACCESS_KEY) {
      return { success: false, error: "API keys not configured" }
    }

    // Generate the blog post content using OpenRouter AI
    const blogData = await generateBlogPost(timeOfDay)

    // Get a relevant image from Unsplash
    const imageUrl = await getUnsplashImage(blogData.topic)

    // Download and save the image
    let imagePath = null
    if (imageUrl) {
      const fileName = `${slugify(blogData.title, { lower: true })}.jpg`
      imagePath = await downloadAndSaveImage(imageUrl, fileName)
    }

    // Generate a slug from the title
    const slug = slugify(blogData.title, { lower: true, strict: true })

    // Prepare the blog post data
    const postData = {
      title: blogData.title,
      slug,
      content: blogData.content,
      excerpt: blogData.excerpt,
      tags: blogData.tags,
      category: blogData.category,
      imagePath: imagePath || "/placeholder.svg?height=600&width=1200&text=Web+Development",
      author: "Ngoma Benjamin",
      authorImage: "/placeholder.svg?height=100&width=100&text=NB",
      authorBio: "Full-stack developer and founder of 301Inc with a passion for web technologies.",
      date: new Date().toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      }),
      readTime: `${Math.max(1, Math.ceil(blogData.content.length / 1000))} min read`,
      status: "published",
      featured: false,
      autoGenerated: true,
      generatedAt: new Date().toISOString(),
      timeOfDay,
    }

    // Save the blog post
    const id = await saveData("blog", postData)

    // Log the activity
    await logActivity("created", "blog", id, postData.title)

    // Notify subscribers about the new post
    try {
      const { sendNewsletterToAll } = await import("./email")
      const subject = `New Blog Post: ${postData.title}`
      const content = `
        <p>Hello,</p>
        <p>A new blog post has been published on Ngoma Benjamin's portfolio website:</p>
        <h2>${postData.title}</h2>
        <p>${postData.excerpt}</p>
        <p>Click the button below to read the full article:</p>
      `

      await sendNewsletterToAll(subject, content, [postData])
    } catch (emailError) {
      console.error("Error sending blog post notification:", emailError)
      // Continue even if email fails
    }

    return { success: true, id }
  } catch (error) {
    console.error("Error generating and publishing blog post:", error)
    return { success: false, error: error.message }
  }
}
